openapi: 3.0.1
info:
  title: Small Business Decision Enhancer API
  description: >-
    API for retrieving small business performance metrics such as daily, weekly, monthly and yearly metrics.
    These metrics detail information such as the number of transactions, amount spent and the breakdown of types of
    transactions at these locations.
  contact:
    name: API Support
    url: https://developer.mastercard.com
    email: apisupport@mastercard.com
  version: 1.0.0

servers:
  - url: sandbox.api.mastercard.com/sbde/metrics-api
    description: Sandbox server (testing environment)
  - url: api.mastercard.com/sbde/metrics-api
    description: Production server (uses live data)

tags:
  - name: merchantLocation
    description: Everything about the merchant's location such as name, address, contact details, etc
  - name: merchantLocationMetrics
    description: Available metrics for a merchant's location
  - name: merchantLocationPerformanceMetrics
    description: >-
      Everything about a merchant's location and performance metrics such as name, address, contact details,
      daily metrics, weekly metrics, etc
paths:
  /merchant-locations/{merchant_location_id}:
    get:
      summary: Get merchant information by merchant_location_id
      description: Returns information about a merchant location based on the merchant_location_id.
      tags:
        - merchantLocation
      operationId: getMerchantLocationByMerchantLocationId
      parameters:
        - $ref: '#/components/parameters/MerchantLocationIdParam'
      responses:
        200:
          $ref: '#/components/responses/MerchantLocation'
        400:
          $ref: '#/components/responses/MerchantLocationBadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        default:
          description: An error occurred. See the status code and the service documentation for more information.

  /merchant-locations/{merchant_location_id}/metrics/daily-metrics:
    get:
      summary: Get merchant daily metrics by merchant_location_id
      description: >-
        Returns the daily metrics for a location using the locations merchant_location_id. The results are configurable
        by page size (limit), offset and sorted by +period for ascending or -period for descending.
        The window size for retrieving results is also configurable by setting the initial date (from_date) as well
        as the last date (to_date).
      tags:
        - merchantLocationMetrics
      operationId: getMerchantLocationDailyMetricsByMerchantLocationId
      parameters:
        - $ref: '#/components/parameters/MerchantLocationIdParam'
        - $ref: '#/components/parameters/FromDateParam'
        - $ref: '#/components/parameters/ToDateParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/offsetParam'
        - $ref: '#/components/parameters/sortParam'
      responses:
        200:
          $ref: '#/components/responses/MerchantLocationDailyMetrics'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        default:
          description: An error occurred. See the status code and the service documentation for more information.

  /merchant-locations/{merchant_location_id}/metrics/weekly-metrics:
    get:
      summary: Get weekly metrics for a location by merchant_location_id
      description: >-
        Returns the weekly metrics for a location using the locations merchant_location_id. The results are configurable
        by page size (limit), offset and sorted by +period for ascending or -period for descending.
        The window size for retrieving results is also configurable by setting the initial date (from_date) as well
        as the last date (to_date).
      tags:
        - merchantLocationMetrics
      operationId: getMerchantLocationWeeklyMetricsByMerchantLocationId
      parameters:
        - $ref: '#/components/parameters/MerchantLocationIdParam'
        - $ref: '#/components/parameters/FromDateParam'
        - $ref: '#/components/parameters/ToDateParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/offsetParam'
        - $ref: '#/components/parameters/sortParam'
      responses:
        200:
          $ref: '#/components/responses/MerchantLocationWeeklyMetrics'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        default:
          description: An error occurred. See the status code and the service documentation for more information.

  /merchant-locations/{merchant_location_id}/metrics/monthly-metrics:
    get:
      summary: Get monthly metrics for a location by merchant_location_id
      description: >-
        Returns the monthly metrics for a location using the locations merchant_location_id. The results are configurable
        by page size (limit), offset and sorted by +period for ascending or -period for descending.
        The window size for retrieving results is also configurable by setting the initial date (from_date) as well
        as the last date (to_date).
      tags:
        - merchantLocationMetrics
      operationId: getMerchantLocationMonthlyMetricsByMerchantLocationId
      parameters:
        - $ref: '#/components/parameters/MerchantLocationIdParam'
        - $ref: '#/components/parameters/FromDateParam'
        - $ref: '#/components/parameters/ToDateParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/offsetParam'
        - $ref: '#/components/parameters/sortParam'
      responses:
        200:
          $ref: '#/components/responses/MerchantLocationMonthlyMetrics'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        default:
          description: An error occurred. See the status code and the service documentation for more information.

  /merchant-locations/{merchant_location_id}/metrics/yearly-metrics:
    get:
      summary: Get yearly metrics for a location by merchant_location_id
      description: >-
        Returns the yearly metrics for a location using the locations merchant_location_id. The results are configurable
        by page size (limit), offset and sorted by +period for ascending or -period for descending.
        The window size for retrieving results is also configurable by setting the initial date (from_date) as well
        as the last date (to_date).
      tags:
        - merchantLocationMetrics
      operationId: getMerchantLocationYearlyMetricsByMerchantLocationId
      parameters:
        - $ref: '#/components/parameters/MerchantLocationIdParam'
        - $ref: '#/components/parameters/FromDateParam'
        - $ref: '#/components/parameters/ToDateParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/offsetParam'
        - $ref: '#/components/parameters/sortParam'
      responses:
        200:
          $ref: '#/components/responses/MerchantLocationYearlyMetrics'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        default:
          description: An error occurred. See the status code and the service documentation for more information.

  /merchant-locations/{merchant_location_id}/metrics/merchant-performance-metrics:
    get:
      summary: Get merchant performance metrics by merchant_location_id
      description: >-
        Returns all available merchant performance metrics for a location using the locations merchant_location_id.
        The results are sorted by +period for ascending or -period for descending. The window size for retrieving
        results is also configurable by setting the initial date (from_date) as well as the last date (to_date).
      tags:
        - merchantLocationPerformanceMetrics
      operationId: getPerformanceMetricsByMerchantLocationId
      parameters:
        - $ref: '#/components/parameters/MerchantLocationIdParam'
        - $ref: '#/components/parameters/FromDateParam'
        - $ref: '#/components/parameters/ToDateParam'
        - $ref: '#/components/parameters/sortParam'
      responses:
        200:
          $ref: '#/components/responses/MerchantLocationPerformanceMetrics'
        400:
          $ref: '#/components/responses/PerformanceMetricsBasRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        default:
          description: An error occurred. See the status code and the service documentation for more information.

components:
  parameters:
    MerchantLocationIdParam:
      name: merchant_location_id
      in: path
      description: Merchant Market Hierarchy ID, used as a matching key
      required: true
      schema:
        type: integer
        format: int64
        minimum: 0
      example: 123456789
    FromDateParam:
      name: from_date
      in: query
      description: Initial date for the window to retrieve the metrics for in ISO8601 format. When excluded the current date is used.
      required: false
      schema:
        type: string
        format: date
      example: '2020-01-01'
    ToDateParam:
      name: to_date
      in: query
      description: End date for the window to retrieve the metrics for in ISO8601 format. When excluded the end date will be 3 years from the `from_date`.
      required: false
      schema:
        type: string
        format: date
      example: '2017-01-01'
    offsetParam:
      name: offset
      in: query
      description: Number of items to skip before returning the results.
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0
      example: 0
    limitParam:
      name: limit
      in: query
      description: Maximum number of items to return.
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        default: 20
      example: 20
    sortParam:
      in: query
      name: sort
      description: Sort order for the metrics. Use -field for sort by field descending and +field for sorting by field ascending. Multiple field are separated by ','.
      required: false
      schema:
        type: string
        default: -period
      example: -period

  responses:
    MerchantLocation:
      description: Information for this Location
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MerchantLocation'

    MerchantLocationDailyMetrics:
      description: Page of daily metrics at this location
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MerchantLocationDailyMetrics'
    MerchantLocationWeeklyMetrics:
      description: Page of weekly metrics at this location
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MerchantLocationWeeklyMetrics'
    MerchantLocationMonthlyMetrics:
      description: Page of monthly metrics at this location
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MerchantLocationMonthlyMetrics'
    MerchantLocationYearlyMetrics:
      description: Page of yearly metrics at this location
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MerchantLocationYearlyMetrics'
    MerchantLocationPerformanceMetrics:
      description: Merchant Location Performance metrics at this location
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MerchantLocationPerformanceMetrics'
    NotFoundError:
      description: URI didn't match an existing resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            Errors:
              - Error:
                  Source: dw-small-business-decision-enhancer-api
                  ReasonCode: RESOURCE_NOT_FOUND
                  Description: "You requested something we don't have"
                  Recoverable: false
                  Details: null

    MerchantLocationBadRequestError:
      description: Something was wrong with the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            Errors:
              - Error:
                  Source: dw-small-business-decision-enhancer-api
                  ReasonCode: INVALID_REQUEST
                  Description: "Method argument type is invalid"
                  Recoverable: true
                  Details: null
    PerformanceMetricsBasRequestError:
      description: Something was wrong with the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            Errors:
              - Error:
                  Source: dw-small-business-decision-enhancer-api
                  ReasonCode: INVALID_REQUEST
                  Description: "Method argument type is invalid"
                  Recoverable: true
                  Details: null
              - Error:
                  Source: dw-small-business-decision-enhancer-api
                  ReasonCode: INVALID_REQUEST_PARAMETER
                  Description: "Sort can only be +, - followed by field names and separated by ,"
                  Recoverable: true
                  Details: null
    BadRequestError:
      description: Something was wrong with the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            Errors:
              - Error:
                  Source: dw-small-business-decision-enhancer-api
                  ReasonCode: INVALID_REQUEST
                  Description: "Method argument type is invalid"
                  Recoverable: true
                  Details: null
              - Error:
                  Source: dw-small-business-decision-enhancer-api
                  ReasonCode: INVALID_REQUEST_PARAMETER
                  Description: "Sort can only be +, - followed by field names and separated by ,"
                  Recoverable: true
                  Details: null
              - Error:
                  Source: dw-small-business-decision-enhancer-api
                  ReasonCode: INVALID_REQUEST_PARAMETER
                  Description: "Offset index must not be less than zero"
                  Recoverable: true
                  Details: null
              - Error:
                  Source: dw-small-business-decision-enhancer-api
                  ReasonCode: INVALID_REQUEST_PARAMETER
                  Description: "Limit must not be less than one"
                  Recoverable: true
                  Details: null
    UnauthorizedError:
      description: Authentication information was missing or invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            Errors:
              - Error:
                  Source: dw-small-business-decision-enhancer-api
                  ReasonCode: UNAUTHORIZED
                  Description: "We couldn't recognize you"
                  Recoverable: false
                  Details: "Full authentication is required to access this resource"
    ForbiddenError:
      description: Insufficient permissions for interacting with the resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            Errors:
              - Error:
                  Source: dw-small-business-decision-enhancer-api
                  ReasonCode: PERMISSION_DENIED
                  Description: "You don't seem authorized to do that"
                  Recoverable: false
                  Details: "Reading merchant information requires readonly permissions"

  schemas:
    ErrorResponse:
      description: Only returned in the event of an error condition
      type: object
      required:
        - Errors
      properties:
        Errors:
          type: object
          required:
            - Error
          properties:
            Error:
              $ref: '#/components/schemas/Errors'
    Errors:
      type: array
      minItems: 1
      description: Only returned in the event of an error condition
      items:
        $ref: '#/components/schemas/Error'
    Error:
      type: object
      description: >-
        Details of the error condition such as the source of the error, reason code for the error,
        if the error is recoverable, and details about the error
      required:
        - Source
        - ReasonCode
        - Description
        - Recoverable
      properties:
        Source:
          description: The application that generated this error
          type: string
          minLength: 0
          maxLength: 150
        ReasonCode:
          description: A unique constant identifying the error case encountered during transaction processing
          type: string
          minLength: 0
          maxLength: 150
        Description:
          description: Short description of the ReasonCode field
          type: string
          minLength: 0
          maxLength: 150
        Recoverable:
          description: Indicates whether this error will always be returned for this request, or retrying could change the outcome
          type: boolean
        Details:
          description: Description of the issue
          type: string
          minLength: 0
          maxLength: 150

    MerchantLocation:
      description: Available information about this location such as the name, address and contact details.
      type: object
      required:
        - merchantLocationId
        - countryCode
      properties:
        merchantLocationId:
          description: Merchant Market Hierarchy ID, used as a matching key
          type: integer
          format: int64
          example: 123456789
        merchantName:
          description: Scrubbed merchant name from transaction clearing data
          type: string
          minLength: 0
          maxLength: 25
          example: "ACME CORP. #1234"
        cleansedMerchantName:
          description: Cleansed name (after cleansing and third-party data validation process)
          type: string
          minLength: 0
          maxLength: 110
          example: "ACME CORPORATION # 1234"
        streetAddr:
          description: Scrubbed merchant address from transaction clearing data
          type: string
          minLength: 0
          maxLength: 48
          example: "10 ROAD RUNNER AVE."
        cleansedStreetAddr:
          description: Cleansed address (after cleansing and third-party data validation process)
          type: string
          minLength: 0
          maxLength: 110
          example: "10 ROAD RUNNER AVENUE"
        cityName:
          description: Scrubbed merchant city from transaction clearing data
          type: string
          minLength: 0
          maxLength: 50
          example: "BIRDVILLE"
        cleansedCityName:
          description: Cleansed city name (after cleansing and third-party data validation process)
          type: string
          minLength: 0
          maxLength: 65
          example: "BIRDVILLE"
        stateName:
          description: Scrubbed merchant state/county from transaction clearing data
          type: string
          minLength: 0
          maxLength: 3
          example: "AZ"
        cleansedStateName:
          description: Cleansed state/county (after cleansing and third-party data validation process)
          type: string
          minLength: 0
          maxLength: 3
          example: "AZ"
        postalCode:
          description: Scrubbed merchant postal/ZIP code from transaction clearing data
          type: string
          minLength: 0
          maxLength: 10
          example: "65543"
        cleansedPostalCode:
          description: Cleansed postal/ZIP code (after cleansing and third-party data validation process)
          type: string
          minLength: 0
          maxLength: 10
          example: "65543"
        countryCode:
          description: Scrubbed merchant country code from transaction clearing data
          type: string
          minLength: 0
          maxLength: 3
          example: "USA"
        cleansedCountryCode:
          description: Cleansed country code (after cleansing and third-party data validation process)
          type: string
          minLength: 0
          maxLength: 3
          example: "USA"
        phoneNumber:
          description: The Merchant phone number after it has been cleaned via matches to third party data
          type: string
          minLength: 0
          maxLength: 16
          example: "9995551234"
        cleansedPhoneNumber:
          description: Cleansed telephone number (after cleansing and third-party data validation process)
          type: string
          minLength: 0
          maxLength: 16
          example: "9995551234"
        mccCode:
          description: Merchant Category Code as reported in the transaction clearing record.
          type: string
          minLength: 0
          maxLength: 8
          example: "5661"
        legalCorporateName:
          description: The merchant legal name as it appears in the clearing record
          type: string
          minLength: 0
          maxLength: 30
          example: "ACME CORP"
        cleansedLegalCorporateName:
          description: The merchant legal name as it appears after it has been cleaned via matches to third party data
          type: string
          minLength: 0
          maxLength: 90
          example: "ACME CORPORATION"
        industry:
          description: MasterCard-defined grouping of Merchant Category Codes  - Approx. 100 categories
          type: string
          minLength: 0
          maxLength: 3
          example: "SHS"
        superIndustry:
          description: MasterCard-defined grouping of Merchant Category Codes  - Approx. 30 categories
          type: string
          minLength: 0
          maxLength: 3
          example: "APP"
        dunAndBradstreetNumber:
          description: Dun and Bradstreet number for Merchant
          type: string
          minLength: 0
          maxLength: 9
          example: "123456789"
        dateEstablished:
          description: First date of transaction seen at merchant in ISO8601 format
          type: string
          format: date
          minLength: 10
          maxLength: 10
          example: 2020-01-31
        terminationDateWithMC:
          description: Date of last transaction seen at merchant as of report date in ISO8601 format
          type: string
          format: date
          minLength: 10
          maxLength: 10
          example: 2020-01-31
        newBusinessFlag:
          description: Indicates whether the location is a 'new business' based on the presence of a first transaction in the preceding 30 days.
          type: boolean
          example: false
        aggregateMerchantId:
          description: Merchant Aggregate ID groups merchant locations by chain.  First level of aggregation.
          type: integer
          format: int64
          example: 5999
        aggregateMerchantName:
          description: Name of the Merchant Aggregate chain
          type: string
          minLength: 0
          maxLength: 75
          example: "NON-AGGREGATED MISCELLANEOUS AND SPECIALTY RETAIL STORES 5999"
        keyAggregateMerchantID:
          description: Joins together different channels under the same chain. Second level of aggregation.
          type: integer
          format: int64
          nullable: true
          example: null
        parentAggregateMerchantId:
          description: ID Code of the Parent Aggregate
          type: string
          minLength: 0
          maxLength: 8
          nullable: true
          example: null
        parentAggregateMerchantName:
          description: Name of the Parent Aggregate
          type: string
          minLength: 0
          maxLength: 75
          nullable: true
          example: null
        naicsCode:
          description: NAICS code
          type: string
          minLength: 0
          maxLength: 6
          example: "45399"
        localFavorite:
          description: Indicates whether the restaurant is frequented by, and popular with, the local population.
          type: boolean
          example: false
        hiddenGeme:
          description: Those local favorites that are in a condensed trade area.
          type: boolean
          example: false
        transactionVolumeRank:
          description: Identifies the relative size of the merchant location based on transaction volume. Buckets of 0-99. (Compares merchants within the same industry category and country)
          type: integer
          format: int32
          example: 75
        avgTicketSizeRank:
          description: Identifies the relative size of the merchant location based on average ticket size. Buckets of 0-99. (Compares merchants within the same industry category and country)
          type: integer
          format: int32
          example: 64

    MerchantLocationMetric:
      description: Basic metrics for a merchant location metrics result
      type: object
      required:
        - merchantLocationId
        - period
      properties:
        merchantLocationId:
          description: The location ID of the merchant
          type: integer
          format: int64
          example: 123456789
        period:
          description: The time period that a metric is associated with
          type: string
          format: date
          minLength: 10
          maxLength: 10
          example: 2020-03-13

    MerchantLocationDailyMetric:
      allOf:
        - $ref: '#/components/schemas/MerchantLocationMetric'
        - type: object
          description: >-
            Metrics for this location on this day such as the total number of transactions and the total amount spent
          required:
            - totalNumberOfTrxs
            - totalTrxsSpend
          properties:
            totalNumberOfTrxs:
              description: The number of transactions that occurred at this location on this day
              type: integer
              format: int64
              example: 19
            totalTrxsSpend:
              description: The total amount spent at this location on this day
              type: number
              format: double
              example: 344.04

    MerchantLocationWeeklyMetric:
      allOf:
        - $ref: '#/components/schemas/MerchantLocationMetric'
        - type: object
          description: >-
            Metrics for this location over this week such as number of transactions, amount spent, and breakdown of
            percentage of in person, credit, debit and online transactions.
          required:
            - totalNumberOfTrxs
            - totalTrxsSpend
            - brickPctSpend
            - brickPctTrxs
            - creditPctSpend
            - creditPctTrxs
            - debitPctSpend
            - debitPctTrxs
            - onlinePctSpend
            - onlinePctTrxs
          properties:
            totalNumberOfTrxs:
              description: The number of transactions that occurred at this location during this week
              type: integer
              format: int64
              example: 19
            totalTrxsSpend:
              description: The total amount spent at this location during this week
              type: number
              format: double
              example: 344.04
            brickPctSpend:
              description: The percentage of spend at this location which was done in person during this week
              type: number
              format: double
              example: 100.0
            brickPctTrxs:
              description: The percentage of in person transactions at this location during this week
              type: number
              format: double
              example: 100.0
            creditPctSpend:
              description: The percentage of spend at this location of which was credit during this week
              type: number
              format: double
              example: 18.9
            creditPctTrxs:
              description: The percentage of transactions at this location of which was credit during this week
              type: number
              format: double
              example: 16.34
            debitPctSpend:
              description: The percentage of spend at this location of which was debit during this week
              type: number
              format: double
              example: 81.1
            debitPctTrxs:
              description: The percentage of transactions at this location of which was debit during this week
              type: number
              format: double
              example: 83.66
            onlinePctSpend:
              description: The percentage of spend at this location of which was online during this week
              type: number
              format: double
              example: 0.0
            onlinePctTrxs:
              description: The percentage of transactions at this location of which was online during this week
              type: number
              format: double
              example: 0.0

    MerchantLocationMonthlyMetric:
      allOf:
        - $ref: '#/components/schemas/MerchantLocationMetric'
        - type: object
          description: >-
            Metrics for this location over this month such as number of transactions, average frequency of transactions
            and the percent of repeat customers
          required:
            - totalNumberOfTrxs
            - totalTrxsSpend
            - avgFrequency
            - pctRepeatCustomers30Days
            - pctRepeatCustomers60Days
            - pctRepeatCustomers90Days
          properties:
            totalNumberOfTrxs:
              description: The number of transactions that occurred at this location during this month
              type: integer
              format: int64
              example: 19
            totalTrxsSpend:
              description: The total amount spent at this location during this month
              type: number
              format: double
              example: 344.04
            avgFrequency:
              description: The average frequency of transactions at this location during this month
              type: number
              format: double
              example: 0.0
            pctRepeatCustomers30Days:
              description: Percentage of repeat customer spend over the previous 30 day period during this month
              type: number
              format: double
              example: 39.68
            pctRepeatCustomers60Days:
              description: Percentage of repeat customer spend over the previous 60 day period during this month
              type: number
              format: double
              example: 42.04
            pctRepeatCustomers90Days:
              description: Percentage of repeat customer spend over the previous 90 day period during this month
              type: number
              format: double
              example: 44.49
            cardProducts:
              description: List of card products for all transactions during this month
              type: array
              items:
                $ref: '#/components/schemas/CardProduct'

    MerchantLocationYearlyMetric:
      allOf:
        - $ref: '#/components/schemas/MerchantLocationMetric'
        - type: object
          description: Index metrics for this location over this year
          required:
            - cardProfileAnualSpendIndex
            - cardProfileAvgTicketIndex
            - cardProfileAnualPurchaseIndex
          properties:
            cardProfileAnualSpendIndex:
              description: The anual spend index at this location during this year
              type: number
              format: double
              example: 1.0
            cardProfileAvgTicketIndex:
              description: The average ticket index at this location during this year
              type: number
              format: double
              example: 2.0
            cardProfileAnualPurchaseIndex:
              description: The anual purchase index at this location during this year
              type: number
              format: double
              example: 3.0

    CardProduct:
      description: Card Product
      type: object
      required:
        - product
        - pctTrxs
        - pctSpend
      properties:
        product:
          description: The name of this card product
          type: string
          minLength: 1
          maxLength: 30
          example: CONSUMER DEBIT
        pctTrxs:
          description: The percentage of tranactions using this card product
          type: number
          format: double
          example: 72.46
        pctSpend:
          description: The percentage spent using this card product
          type: number
          format: double
          example: 71.57

    Page:
      description: Base response for a paged response
      type: object
      required:
        - limit
        - offset
        - total
      properties:
        limit:
          type: integer
          format: int32
          example: 20
        offset:
          type: integer
          format: int32
          example: 0
        total:
          type: integer
          format: int64
          example: 70

    MerchantLocationDailyMetrics:
      allOf:
        - $ref: '#/components/schemas/Page'
        - type: object
          description: Paged response of daily metrics at this location
          required:
            - items
          properties:
            items:
              type: array
              description: Array of merchant daily metrics
              items:
                $ref: '#/components/schemas/MerchantLocationDailyMetric'

    MerchantLocationWeeklyMetrics:
      allOf:
        - $ref: '#/components/schemas/Page'
        - type: object
          description: Paged response of weekly metrics at this location
          required:
            - items
          properties:
            items:
              type: array
              description: Array of merchant weekly metrics
              items:
                $ref: '#/components/schemas/MerchantLocationWeeklyMetric'

    MerchantLocationMonthlyMetrics:
      allOf:
        - $ref: '#/components/schemas/Page'
        - type: object
          description: Paged response of monthly metrics at this location
          required:
            - items
          properties:
            items:
              type: array
              description: Array of merchant monthly metrics
              items:
                $ref: '#/components/schemas/MerchantLocationMonthlyMetric'

    MerchantLocationYearlyMetrics:
      allOf:
        - $ref: '#/components/schemas/Page'
        - type: object
          description: Paged response of yearly metrics at this location
          required:
            - items
          properties:
            items:
              type: array
              description: Array of merchant yearly metrics
              items:
                $ref: '#/components/schemas/MerchantLocationYearlyMetric'

    MerchantLocationDailyPerformanceMetric:
      type: object
      description: >-
        Metrics for this location on this day such as the total number of transactions and the total amount spent
      required:
        - period
        - totalNumberOfTrxs
        - totalTrxsSpend
      properties:
        period:
          description: The time period that a metric is associated with
          type: string
          format: date
          minLength: 10
          maxLength: 10
          example: 2020-03-13
        totalNumberOfTrxs:
          description: The number of transactions that occurred at this location on this day
          type: integer
          format: int64
          example: 19
        totalTrxsSpend:
          description: The total amount spent at this location on this day
          type: number
          format: double
          example: 344.04

    MerchantLocationWeeklyPerformanceMetric:
      type: object
      description: >-
        Metrics for this location over this week such as number of transactions, amount spent, and breakdown of
        percentage of in person, credit, debit and online transactions.
      required:
        - period
        - totalNumberOfTrxs
        - totalTrxsSpend
        - brickPctSpend
        - brickPctTrxs
        - creditPctSpend
        - creditPctTrxs
        - debitPctSpend
        - debitPctTrxs
        - onlinePctSpend
        - onlinePctTrxs
      properties:
        period:
          description: The time period that a metric is associated with
          type: string
          format: date
          minLength: 10
          maxLength: 10
          example: 2020-03-13
        totalNumberOfTrxs:
          description: The number of transactions that occurred at this location during this week
          type: integer
          format: int64
          example: 19
        totalTrxsSpend:
          description: The total amount spent at this location during this week
          type: number
          format: double
          example: 344.04
        brickPctSpend:
          description: The percentage of spend at this location which was done in person during this week
          type: number
          format: double
          example: 100.0
        brickPctTrxs:
          description: The percentage of in person transactions at this location during this week
          type: number
          format: double
          example: 100.0
        creditPctSpend:
          description: The percentage of spend at this location of which was credit during this week
          type: number
          format: double
          example: 18.9
        creditPctTrxs:
          description: The percentage of transactions at this location of which was credit during this week
          type: number
          format: double
          example: 16.34
        debitPctSpend:
          description: The percentage of spend at this location of which was debit during this week
          type: number
          format: double
          example: 81.1
        debitPctTrxs:
          description: The percentage of transactions at this location of which was debit during this week
          type: number
          format: double
          example: 83.66
        onlinePctSpend:
          description: The percentage of spend at this location of which was online during this week
          type: number
          format: double
          example: 0.0
        onlinePctTrxs:
          description: The percentage of transactions at this location of which was online during this week
          type: number
          format: double
          example: 0.0

    MerchantLocationMonthlyPerformanceMetric:
      type: object
      description: >-
        Metrics for this location over this month such as number of transactions, average frequency of transactions
        and the percent of repeat customers
      required:
        - period
        - totalNumberOfTrxs
        - totalTrxsSpend
        - avgFrequency
        - pctRepeatCustomers30Days
        - pctRepeatCustomers60Days
        - pctRepeatCustomers90Days
      properties:
        period:
          description: The time period that a metric is associated with
          type: string
          format: date
          minLength: 10
          maxLength: 10
          example: 2020-03-13
        totalNumberOfTrxs:
          description: The number of transactions that occurred at this location during this month
          type: integer
          format: int64
          example: 19
        totalTrxsSpend:
          description: The total amount spent at this location during this month
          type: number
          format: double
          example: 344.04
        avgFrequency:
          description: The average frequency of transactions at this location during this month
          type: number
          format: double
          example: 0.0
        pctRepeatCustomers30Days:
          description: Percentage of repeat customer spend over the previous 30 day period during this month
          type: number
          format: double
          example: 39.68
        pctRepeatCustomers60Days:
          description: Percentage of repeat customer spend over the previous 60 day period during this month
          type: number
          format: double
          example: 42.04
        pctRepeatCustomers90Days:
          description: Percentage of repeat customer spend over the previous 90 day period during this month
          type: number
          format: double
          example: 44.49
        cardProducts:
          description: List of card products for all transactions during this month
          type: array
          items:
            $ref: '#/components/schemas/PerformanceMetricsCardProduct'

    PerformanceMetricsCardProduct:
      description: Card Product
      type: object
      required:
        - product
        - pctTrxs
        - pctSpend
      properties:
        product:
          description: The name of this card product
          type: string
          minLength: 1
          maxLength: 30
          example: CONSUMER DEBIT
        pctTrxs:
          description: The percentage of tranactions using this card product
          type: number
          format: double
          example: 72.46
        pctSpend:
          description: The percentage spent using this card product
          type: number
          format: double
          example: 71.57

    LegacyPerformanceMetrics:
      description: List of available merchant location performance metrics for this location
      type: object
      properties:
        mmhid:
          description: Merchant Market Hierarchy ID, used as a matching key
          type: integer
          format: int64
          minimum: 0
          example: 123456789
        dailyMetrics:
          type: array
          items:
            $ref: '#/components/schemas/MerchantLocationDailyPerformanceMetric'
        weeklyMetrics:
          type: array
          items:
            $ref: '#/components/schemas/MerchantLocationWeeklyPerformanceMetric'
        monthlyMetrics:
          type: array
          items:
            $ref: '#/components/schemas/MerchantLocationMonthlyPerformanceMetric'
        cardProfileAnualSpendIndex:
          description: The anual spend index at this location during this year
          type: number
          format: double
          example: 1.0
        cardProfileAvgTicketIndex:
          description: The average ticket index at this location during this year
          type: number
          format: double
          example: 2.0
        cardProfileAnualPurchaseIndex:
          description: The anual purchase index at this location during this year
          type: number
          format: double
          example: 3.0


    MerchantLocationPerformanceMetrics:
      description: All available merchant location performance metrics for this location
      type: object
      properties:
        merchant:
          $ref: '#/components/schemas/MerchantLocation'
        performance:
          $ref: '#/components/schemas/LegacyPerformanceMetrics'